spring:
  main:
    web-application-type: SERVLET


  profiles:
    active: aws

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1


server:
  port: 8080
  error:
    include-message: ALWAYS

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.vishwa.Customer: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.jdbc.datasource: DEBUG

#cors:
#  allowed-origins: "http://localhost:3000"
#  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"


cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

