spring:
  datasource:
    url: jdbc:postgresql://awseb-e-6ctyxmcqhy-stack-awsebrdsdatabase-zwxffx8vdufc.ctnbtczet5qk.ap-south-1.rds.amazonaws.com/customer
    username: vishwaswami
    password: 12345678