spring:
  datasource:
    url: jdbc:postgresql://awseb-e-f3nsmyxe2q-stack-awsebrdsdatabase-jwc3irnrv2d4.ctnbtczet5qk.ap-south-1.rds.amazonaws.com:5432/customer
    username: vishwaswami
    password: 12345678