spring:
  datasource:
    url: jdbc:postgresql://awseb-e-fxuwb7qpgh-stack-awsebrdsdatabase-tvdrel3orn8j.ctnbtczet5qk.ap-south-1.rds.amazonaws.com:5432/customer
    username: vishwaswami
    password: 12345678