spring:
  datasource:
    url: jdbc:postgresql://awseb-e-eyigeqd8ib-stack-awsebrdsdatabase-udnktcs3aolg.ctnbtczet5qk.ap-south-1.rds.amazonaws.com:5432/customer
    username: vishwaswami
    password: 12345678