spring:
  datasource:
    url: jdbc:postgresql://awseb-e-rpqjgcpw52-stack-awsebrdsdatabase-eg2ypg4jstw0.ctnbtczet5qk.ap-south-1.rds.amazonaws.com:5432/customer
    username: vishwaswami
    password: 12345678