spring:
  datasource:
    url: jdbc:postgresql://awseb-e-nmcx4b5cj2-stack-awsebrdsdatabase-nlyglhvbc2b9.ctnbtczet5qk.ap-south-1.rds.amazonaws.com:5432/customer
    username: vishwaswami
    password: 12345678