spring:
  datasource:
    url: jdbc:postgresql://awseb-e-7wmhijhv9h-stack-awsebrdsdatabase-amk73ypbmgx4.ctnbtczet5qk.ap-south-1.rds.amazonaws.com:5432/customer
    username: vishwaswami
    password: 12345678